# Minimal allowlist to reduce noise from generated/vendor files
[allowlist]
paths = [
  "node_modules/",
  "dist/",
  "build/",
  "coverage/",
  "playwright-report/",
  "CHANGELOG.md",
  "pnpm-lock.yaml",
  "package-lock.json",
  "yarn.lock",
  ".*\\.snap$"
]

