title = "MMTU Gitleaks Config"

# Allowlist for test secrets and generated files
[allowlist]
description = "Test keys, generated files & known false positives"
paths = [
  "node_modules/",
  "dist/",
  "build/",
  "coverage/",
  "playwright-report/",
  "CHANGELOG.md",
  "pnpm-lock.yaml",
  "package-lock.json",
  "yarn.lock",
  ".*\\.snap$",
  "test-secret.env",
  "tests/.*",
  ".*fixtures.*", 
  ".*example.*",
  "test-secret.env"
]
regexes = [
  '''(?i)test(_|-)?(key|token|secret)[a-z0-9_\-]{8,}''',
  '''(?i)dummy(pass(word)?|token|secret)''',
  '''(?i)canary[_-]?secret.*'''
]

