# Minimal allowlist to reduce noise from generated/vendor files
[allowlist]
paths = [
  "node_modules/",
  "dist/",
  "build/",
  "coverage/",
  "playwright-report/",
  "CHANGELOG.md",
  ".*\.lock$",
  ".*\.snap$"
]

