title = "MMTU Gitleaks Config"

[allowlist]
description = "Test keys & known false positives"
paths = [
  "tests/.*",
  ".*fixtures.*", 
  ".*example.*"
]
regexes = [
  '''(?i)test(_|-)?(key|token|secret)[a-z0-9_\-]{8,}''',
  '''(?i)dummy(pass(word)?|token|secret)'''
]
