version: "3.9"
services:
  calcom:
    env_file:
      - ops/env/.env.cal  # create locally from .env.cal.example
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/api/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 15s
      timeout: 3s
      retries: 10
      start_period: 20s

  zammad:
    env_file:
      - ops/env/.env.zammad  # create locally from .env.zammad.example
    ports:
      - "8086:3000"  # Direct access for development
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -fsS http://localhost:3000 || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 20
      start_period: 40s