# Traefik Static Configuration
# Docs: https://doc.traefik.io/traefik/reference/static-configuration/

# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: business-ops-network
  file:
    filename: /dynamic.yml
    watch: true

# Certificate resolvers
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@localhost  # Override with ACME_EMAIL environment variable
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web
      # For production, use DNS challenge:
      # dnsChallenge:
      #   provider: cloudflare
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "8.8.8.8:53"

# API and dashboard
api:
  dashboard: true
  insecure: true  # Set to false in production

# Logging
log:
  level: INFO
  filePath: /var/log/traefik/traefik.log

accessLog:
  filePath: /var/log/traefik/access.log

# Metrics (optional)
# metrics:
#   prometheus:
#     addEntryPointsLabels: true
#     addServicesLabels: true
#     entryPoint: metrics

# Pilot (optional)
# pilot:
#   token: "xxxx"

# Tracing (optional)
# tracing:
#   jaeger:
#     samplingServerURL: http://jaeger:14268/api/sampling
#     localAgentHostPort: jaeger:6831