# Portfolio Monitoring URLs

Generated by Terraform - Portfolio Observability Infrastructure

## Dashboard
- **Portfolio Dashboard:** ${dashboard_url}
- **DORA Metrics:** ${dashboard_url}/dora-metrics
- **Alerts Center:** ${dashboard_url}/alerts

## Health Checks
%{ for product_id, check in health_checks ~}
- **${check.name}:** ${check.address}
%{ endfor ~}

## Monitoring Tools
- **GitHub Actions:** https://github.com/MMTUEntertainment/portfolio-dashboard/actions
- **Cloudflare Analytics:** https://dash.cloudflare.com/
- **PostHog Analytics:** https://app.posthog.com/

## Alerting
- Cloudflare notifications configured for uptime monitoring
- GitHub Issues automatically created for critical alerts
- Slack notifications (if configured)

## Quick Access
- **GitHub Organization:** https://github.com/MMTUEntertainment
- **Infrastructure Repository:** https://github.com/MMTUEntertainment/portfolio-dashboard

---
*Last updated: $(date)*