name = "driftguard-marketplace-webhook"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Production deployment
[env.production]
routes = [
  { pattern = "api.mmtuentertainment.com/webhooks/marketplace", zone_name = "mmtuentertainment.com" }
]

# Development environment
[env.dev]
routes = [
  { pattern = "dev-api.mmtuentertainment.com/webhooks/marketplace", zone_name = "mmtuentertainment.com" }
]

# Environment variables (set via wrangler secret)
# Required secrets:
# - GITHUB_WEBHOOK_SECRET: GitHub webhook secret for signature verification
# - SUPABASE_URL: Supabase project URL
# - SUPABASE_SERVICE_ROLE_KEY: Supabase service role key
# - POSTHOG_PROJECT_ID: PostHog project identifier  
# - POSTHOG_API_KEY: PostHog API key for event tracking