name = "driftguard-checks"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# KV Namespace for caching and rate limiting
[[kv_namespaces]]
binding = "CACHE"
id = "2df5e78ed8f14958a07a995e1c116bd0"

# D1 Database for user data and audit logs
[[d1_databases]]
binding = "DB"
database_name = "driftguard-prod"
database_id = "7b2c7252-a010-45d7-9426-b9164e9f9e62"

# R2 Bucket for CTRF artifacts and reports (disabled until R2 is enabled)
# [[r2_buckets]]
# binding = "ARTIFACTS"
# bucket_name = "driftguard-artifacts"

# Environment variables (non-sensitive)
[vars]
# ===== REPLACE THESE VALUES WITH YOUR ACTUAL CREDENTIALS =====

# GitHub App ID (numeric ID from GitHub App settings)
GITHUB_APP_ID = "1789837"

# Stripe publishable key (safe for client-side, starts with pk_test_ or pk_live_)
STRIPE_PUBLISHABLE_KEY = "pk_test_51RwZ2E5MhhpPoQHl1zGWoKuOj4hlGGoooV6CooumKhVrpnPdtdxlyxxvD94kBykNxU42pL3sEmEJzXOalY2W6UPF00ECLUKm5D"

# Supabase project URL (https://xxxxx.supabase.co)
SUPABASE_URL = "https://tnebqbkbofwnsuvylext.supabase.co"

# Supabase anonymous key (starts with eyJhbGciOiJIUzI1NiIs...)
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuZWJxYmtib2Z3bnN1dnlsZXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDY4NDUsImV4cCI6MjA3MDg4Mjg0NX0.C5NMXgvAdxL-p37bY2ghjJggbsw7mhfLzwCZB8koq8I"

# PostHog API key (starts with phc_...)
POSTHOG_API_KEY = "phc_GhG69uStkNnzI3TMVHSsRODglQojHJ89zbGAEvVGYYV"

# Environment setting
ENVIRONMENT = "production"

# ===== SECRETS (SET VIA: wrangler secret put <name>) =====
# These are configured separately using the configure-secrets.sh script:
# - GITHUB_PRIVATE_KEY (contents of your .pem file)
# - GITHUB_WEBHOOK_SECRET (from GitHub App webhook settings)
# - STRIPE_SECRET_KEY (sk_test_... or sk_live_...)
# - STRIPE_WEBHOOK_SECRET (whsec_... from Stripe webhook settings)
# - SUPABASE_SERVICE_KEY (service_role key from Supabase project settings)