name: billing-smoke
on:
  pull_request:
    paths:
      - 'functions/api/billing/**'
      - 'services/billing/**'
      - 'products/site/**'
      - 'legal/BILLING.md'
      - '.github/workflows/billing-smoke.yml'
  workflow_dispatch: {}

concurrency:
  group: billing-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm run -r lint || echo "lint script not found; skipping"

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm exec tsc -v && pnpm exec tsc -noEmit || echo "no tsconfig; skipping"

  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm dlx playwright install --with-deps chromium
      - run: pnpm exec playwright test -c products/site/playwright.config.ts -g "billing smoke" --project=chromium --reporter=line

