name: docs-checks
on:
  pull_request:
    paths:
      - "docs/**"
      - "**/*.md"
  workflow_dispatch: {}
concurrency:
  group: docs-checks-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  spell:
    name: Spell check (cspell)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cspell
        uses: streetsidesoftware/cspell-action@v7.2.0
        with:
          config: "cspell.json"
          incremental_files_only: true

  links:
    name: Link check (lychee)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: lychee
        uses: lycheeverse/lychee-action@v2.5.0
        with:
          args: >
            --config docs/lychee.toml
            --exclude-file .lycheeignore
            --verbose --no-progress
            docs README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs-ci:
    name: docs-ci
    runs-on: ubuntu-latest
    needs: [spell, links]
    if: ${{ always() }}
    steps:
      - name: Aggregate status
        shell: bash
        run: |
          echo "spell=${{ needs.spell.result }}"
          echo "links=${{ needs.links.result }}"
          if [ "${{ needs.spell.result }}" != "success" ] || [ "${{ needs.links.result }}" != "success" ]; then
            echo "One or more checks failed."
            exit 1
          fi
