name: Docs Checks

on:
  pull_request:
    paths:
      - "**/*.md"
      - "docs/**"
      - ".lycheeignore"
      - ".github/workflows/docs-checks.yml"
  merge_group:
    paths:
      - "**/*.md"
      - "docs/**"
      - ".lycheeignore"
      - ".github/workflows/docs-checks.yml"

concurrency:
  group: docs-checks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs-ci:
    name: docs-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20'
      
      - name: Install cspell
        run: npm install -g cspell@7.2.0
      
      - name: Spell check
        run: cspell "**/*.md" --no-progress --show-suggestions --gitignore
      
      - name: Link check
        uses: lycheeverse/lychee-action@7da8ec1fc4e01b5a12062ac6c589c10a4ce70d67 # v1.10.0
        with:
          args: --verbose --no-progress --exclude-file .lycheeignore "**/*.md"