name: Weekly Market Digest
on:
  schedule:
    - cron: '0 9 * * 1'  # Monday 9 AM UTC
  workflow_dispatch:

jobs:
  generate-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate decisions digest
        run: |
          {
            echo "# Weekly Decisions Digest - $(date)"
            echo "## Active Bets Status"
            gh project view "Business Action Tracks – 2025H2" --json items | jq '.items[] | select(.status=="Active")'
            echo "## Completed This Week"
            gh project view "Business Action Tracks – 2025H2" --json items | jq '.items[] | select(.status=="Done" and .updatedAt > "'"$(date -d '7 days ago' -Idate)"'")'
            echo "## Governance Metrics"
            ACTIVE_COUNT=$(gh project view "Business Action Tracks – 2025H2" --json items | jq '.items[] | select(.status=="Active")' | wc -l)
            echo "- Active bet count: $ACTIVE_COUNT"
            if [ "$ACTIVE_COUNT" -le 3 ]; then
              echo "- ≤3 bet compliance: ✅ PASS"
            else
              echo "- ≤3 bet compliance: ❌ FAIL"
            fi
            echo "## Weekly Review Actions"
            echo "- [ ] Review kill/scale signals for each active bet"
            echo "- [ ] Assess upside evidence and progress metrics"
            echo "- [ ] Validate circle of competence alignment"
            echo "- [ ] Update bet status based on 4-week cycle rules"
          } > digest.md
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: weekly-digest-${{ github.run_number }}
          path: digest.md